using System.Security.Cryptography;
using System.Text;
using FBSC.ODMS.Application.Features.ODMS.AiSqlGenerationRequest.Commands;
using FBSC.ODMS.Application.Features.ODMS.AiSqlGenerationRequest.Queries;
using FBSC.ODMS.Application.Features.ODMS.DashboardQuery.Commands;
using FBSC.ODMS.Core.Constants;
using FBSC.ODMS.Infrastructure.Services.Dashboard;
using FBSC.ODMS.Web.Areas.ODMS.Models;
using FBSC.ODMS.Web.Models;
using LanguageExt.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static LanguageExt.Prelude;

namespace FBSC.ODMS.Web.Areas.ODMS.Pages.AiSqlGenerationRequest;

[Authorize(Policy = Permission.AiSqlGenerationRequest.View)]
public class DetailsModel(SqlQueryValidator sqlQueryValidator, IAuthorizationService authorizationService) : BasePageModel<DetailsModel>
{
    public AiSqlGenerationRequestViewModel AiSqlGenerationRequest { get; set; } = new();
	[BindProperty]
    public string? RemoveSubDetailId { get; set; }
    [BindProperty]
    public string? AsyncAction { get; set; }
    public async Task<IActionResult> OnGet(string? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        return await PageFrom(async () => await Mediatr.Send(new GetAiSqlGenerationRequestByIdQuery(id)), AiSqlGenerationRequest);
    }

    /// <summary>
    /// Explicit human approval step: turns an AI-generated, PendingApproval SQL text into a
    /// real, widget-usable DashboardQuery. Nothing generated by AI becomes usable on a widget
    /// without going through here.
    /// </summary>
    public async Task<IActionResult> OnPostCreateDashboardQuery(string id)
    {
        if ((await authorizationService.AuthorizeAsync(User, Permission.AiSqlGenerationRequest.Approve)).Succeeded == false)
        {
            return Forbid();
        }

        var loadResult = await Mediatr.Send(new GetAiSqlGenerationRequestByIdQuery(id));
        var request = loadResult.Match(Some: r => r, None: () => null);
        if (request is null)
        {
            return NotFound();
        }
        if (!string.IsNullOrEmpty(request.DashboardQueryId) || string.IsNullOrEmpty(request.GeneratedSqlQueryText))
        {
            NotyfService.Warning(Localizer["This request has no pending generated SQL to approve."]);
            return RedirectToPage(new { id });
        }

        var validation = sqlQueryValidator.Validate(request.GeneratedSqlQueryText);

        var addQueryResult = await TryAsync(async () => await Mediatr.Send(new AddDashboardQueryCommand
        {
            DataSourceId = request.DataSourceId,
            Name = $"AI: {request.NaturalLanguagePrompt}"[..Math.Min(150, $"AI: {request.NaturalLanguagePrompt}".Length)],
            Description = request.NaturalLanguagePrompt,
            SqlQueryText = request.GeneratedSqlQueryText,
            QueryHash = ComputeQueryHash(request.GeneratedSqlQueryText),
            GeneratedByAI = true,
            ValidationStatus = validation.IsValid ? QueryValidationStatus.Valid : QueryValidationStatus.Invalid,
            LastExecutionErrorRemarks = validation.ErrorMessage,
            LastValidatedAt = DateTime.UtcNow,
            IsActive = validation.IsValid,
        })).IfFail(ex =>
        {
            Logger.LogError(ex, "Exception approving AiSqlGenerationRequest {Id}", id);
            return Fail<Error, Core.ODMS.DashboardQueryState>(Localizer["Something went wrong creating the dashboard query."] + $" TraceId = {HttpContext.TraceIdentifier}");
        });

        Core.ODMS.DashboardQueryState? newQuery = null;
        addQueryResult.Match(
            Succ: succ => newQuery = succ,
            Fail: errors => AddModelError(errors, notifyError: true));

        if (newQuery is null)
        {
            return RedirectToPage(new { id });
        }

        await Mediatr.Send(new EditAiSqlGenerationRequestCommand
        {
            Id = request.Id,
            DataSourceId = request.DataSourceId,
            NaturalLanguagePrompt = request.NaturalLanguagePrompt,
            GeneratedSqlQueryText = request.GeneratedSqlQueryText,
            DashboardQueryId = newQuery.Id,
            ConfidenceScore = request.ConfidenceScore,
            ValidationStatus = newQuery.ValidationStatus,
            ErrorRemarks = request.ErrorRemarks,
            RequestedBy = request.RequestedBy,
            GeneratedAt = request.GeneratedAt,
        });
        NotyfService.Success(Localizer["Dashboard query created and linked. It can now be attached to a widget."]);
        return RedirectToPage(new { id });
    }

    private static string ComputeQueryHash(string sqlQueryText) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(sqlQueryText)));
}
